# Content configuration version (darkmode = true/false/never)
version: 2
darkmode: false
favicon: images/favicon.ico
# Personal info
name: Gabriel Forien
title: Student at INSA Lyon, France
email: gforien.pro@gmail.com
# website: www.gforien.github.io
github_username:  gforien
facebook_username: gabriel.forien
instagram_username: gabrielforien
linkedin_username: gforien



#####################
#       BIO
#####################
about_title: Bio
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Bonjour bonjour 👋




#######################
#       PROJETS
#######################
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:


      - title: InShape
        layout: top-middle
        link: https://gforien.github.io/inshape/static/index.html?./images/osi.png
        link_text: Live demo
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/gforien/inshape
        description: |
          J'utilise Miro quotidiennement, aussi bien pour mes cours que mes projets personnels.<br>
          Ce qui me manque, c'est de pouvoir copier/coller une image et qu'elle soit directement modifiable.<br>
          Nous sommes en 2021, et quand je colle un schéma il n'est pas automatiquement reconnu et transformé en formes Miro ?<br>
          J'ai du mal à y croire !<br>
          On peut passer par un peu de traitement d'image pour récupérer les formes, les couleurs, un coup d'OCR, et boum !<br>
          Du coup c'est ce que j'ai fait 😉


      - title: BlueBox
        layout: top-middle
        link: https://gforien.github.io/inshape/static/index.html?./images/osi.png
        link_text: Live demo
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/bluebox-insa
          - title:  instagram
            icon: fab fa-instagram
            url: instagram.com/bluebox_insa
        description: |
          On a tous des enceintes Bluetooth, mais impossible de les connecter ensemble.



########################
#       FORMATION
########################
  - title: Formation
    layout: list
    content:
      - layout: left
        title: INSA Lyon
        caption: 2015 - 2021
        sub_title: Informatique et Télécommunications
        quote: >
          Ce que j'en retiendrai ? Des antennes, de belles rencontres, du code, la Junior-Entreprise, et le lever de soleil sur le campus de la Doua
        description: |
          description



footer_show_references: true
references_title: Made with ❤ by sproogen
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
 - jekyll-seo-tag