# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Gabriel Forien
title: Student at INSA Lyon, France
email: gforien.pro@gmail.com
# website: www.gforien.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  gforien
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: gabriel.forien
# flickr_username: jekyll
instagram_username: gabrielforien
linkedin_username: gforien
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Bio
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Bonjour 👋

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: InShape
        link: https://gforien.github.io/inshape/static/index.html?./images/osi.png
        link_text: Live demo
        additional_links:
          - title: github
            icon: fab fa-github
            url: github.com/gforien/inshape
          - title:  instagram
            icon: fab fa-instagram
            url: instagram.com/
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |
        J utilise Miro quotidiennement, aussi bien pour mes cours que mes projets personnels.
        Ce qui me manque, c'est de pouvoir copier/coller une image et qu'elle soit directement modifiable.
        On est en 2021, pourquoi quand je colle un schéma, il n'est pas automatiquement reconnu et transformé en formes Miro ??
        On peut passer par un peu de traitement d'image pour récupérer les formes, les couleurs, un coup d'OCR, et boum !
        Du coup c'est ce que j'ai fait 😉
# I use Miro a lot, so I often find myself including images or diagrams that are very synthetic, with nice colors and shapes.
# And I'd like to edit these images, instead of being stuck with them. So I created this plugin to turn diagrams into Miro shapes.

  # - title: Experience
  #   layout: list
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Formation # Title for the section
    layout: list
    content:
      - layout: left
        title: INSA Lyon
        caption: 2015 - 2021
        sub_title: Informatique et Télécommunications
        quote: >
          Ce que j'en retiendrai ? Des antennes, de belles rencontres, du code, la Junior-Entreprise, et le lever de soleil sur le campus de la Doua
        description: |
          description


  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: Made with ❤ by sproogen

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
